# standard jekyll configuration options

exclude: ['Rakefile', 'README.md', 'config.rb']

# configuration required for some pages

domain: braiSn.github.io
title: braiSn
author: Collectif braiSn
email: chloe+braisn@tigres-rouges.net

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

# github:
#   username: ghusername

disqus:
  id: braisn
